# Libraries

In [6]:
from bokeh.io import output_notebook
from bokeh.layouts import column, gridplot, layout, row
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, LinearColorMapper, NumeralTickFormatter, Range1d, HoverTool
from bokeh.models import Span, Label, Panel, Tabs, LabelSet, SingleIntervalTicker, LinearAxis, DatetimeTickFormatter
from bokeh.embed import components
from bokeh.transform import cumsum
from bokeh.palettes import Category20
from bokeh.models import Span, Legend
from bokeh.io import curdoc
from bokeh.themes import Theme
import pandas as pd

# Import our data

In [8]:
df = pd.read_csv('data/nyc_weather.csv')
df.head()

,date,actual_mean_temp,actual_min_temp,actual_max_temp,average_min_temp,average_max_temp,record_min_temp,record_max_temp,record_min_temp_year,record_max_temp_year,actual_precipitation,average_precipitation,record_precipitation
0,2014-7-1,81,72,89,68,83,52,100,1943,1901,0.00,0.12,2.17
1,2014-7-2,82,72,91,68,83,56,100,2001,1966,0.96,0.13,1.79
2,2014-7-3,78,69,87,68,83,54,103,1933,1966,1.78,0.12,2.80
3,2014-7-4,70,65,74,68,84,55,102,1986,1949,0.14,0.13,1.76
4,2014-7-5,72,63,81,68,84,53,101,1979,1999,0.00,0.12,3.07